services:
  - type: web
    name: ecobayanihan
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn myproject.wsgi:application
    preDeployCommand: python manage.py migrate && python manage.py setup_data
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: eco-bayanihan.onrender.com,localhost,127.0.0.1
databases:
  - name: ecobayanihan-db
    databaseName: ecobayanihan
    user: ecobayanihan